-- Create wizard tables when this database is empty, then add any missing columns.

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(500),
    description TEXT,
    status VARCHAR(30) NOT NULL,
    last_login_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(255) NOT NULL,
    project_type VARCHAR(30),
    description TEXT,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stakeholder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    role_code VARCHAR(50),
    person_name VARCHAR(255),
    person_email VARCHAR(255),
    code VARCHAR(80),
    name VARCHAR(255),
    category VARCHAR(50),
    active BOOLEAN,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS project_type VARCHAR(30);
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS owner_email VARCHAR(255);
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS wizard_step VARCHAR(80);
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS wizard_completed_through INTEGER;
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS wizard_state_json TEXT;

ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS project_id BIGINT;
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS role_code VARCHAR(50);
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS person_name VARCHAR(255);
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS person_email VARCHAR(255);
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS code VARCHAR(80);
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS active BOOLEAN;
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS updated_by UUID;
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE IF EXISTS stakeholder ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS project_integration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    provider VARCHAR(40) NOT NULL,
    account VARCHAR(255),
    base_url VARCHAR(500),
    email VARCHAR(255),
    username VARCHAR(255),
    organization VARCHAR(255),
    workspace VARCHAR(255),
    project_key VARCHAR(80),
    project_name VARCHAR(255),
    space_key VARCHAR(80),
    cloud_id VARCHAR(120),
    auth_type VARCHAR(40),
    access_token_enc TEXT,
    refresh_token_enc TEXT,
    expires_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_project_integration_provider
    ON project_integration (project_id, provider);

CREATE TABLE IF NOT EXISTS figma_design_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    file_key VARCHAR(80) NOT NULL,
    file_name VARCHAR(255),
    file_url VARCHAR(500),
    figma_project_id VARCHAR(80),
    team_id VARCHAR(80),
    sync_jira BOOLEAN NOT NULL DEFAULT TRUE,
    webhook_id VARCHAR(120),
    webhook_passcode VARCHAR(120),
    file_version VARCHAR(80),
    last_synced_at VARCHAR(40),
    last_sync_summary TEXT,
    webhook_status VARCHAR(120),
    snapshot_json TEXT,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_figma_design_project_file
    ON figma_design_binding (project_id, file_key);
