-- User-level integration connections (survive login; shared across projects).

CREATE TABLE IF NOT EXISTS user_integration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_email VARCHAR(255) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    account VARCHAR(255),
    base_url VARCHAR(500),
    email VARCHAR(255),
    username VARCHAR(255),
    organization VARCHAR(255),
    workspace VARCHAR(255),
    project_key VARCHAR(80),
    project_name VARCHAR(255),
    space_key VARCHAR(80),
    cloud_id VARCHAR(120),
    auth_type VARCHAR(40),
    access_token_enc TEXT,
    refresh_token_enc TEXT,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_integration_owner_provider
    ON user_integration (owner_email, provider);

CREATE INDEX IF NOT EXISTS idx_user_integration_owner
    ON user_integration (lower(owner_email));
