-- Setup co-pilot chat: one thread per project.

CREATE TABLE IF NOT EXISTS chat_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL UNIQUE REFERENCES project (id) ON DELETE CASCADE,
    owner_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_thread_owner
    ON chat_thread (lower(owner_email));

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL REFERENCES chat_thread (id) ON DELETE CASCADE,
    role VARCHAR(40) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    model VARCHAR(80),
    mode VARCHAR(20),
    tool_json JSONB,
    turn_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_message_thread
    ON chat_message (thread_id, id);
