-- Durable AI-SDLC workflow: principals, membership, runs, runners, jobs, outbox.

CREATE TABLE IF NOT EXISTS principal (
    id UUID PRIMARY KEY,
    kind VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    display_name VARCHAR(255) NOT NULL,
    agent_id VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT principal_kind_check CHECK (kind IN ('human', 'agent'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_principal_email
    ON principal (lower(email))
    WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_principal_agent_id
    ON principal (agent_id)
    WHERE agent_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS project_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    principal_id UUID NOT NULL REFERENCES principal (id) ON DELETE CASCADE,
    role_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, principal_id)
);

CREATE INDEX IF NOT EXISTS idx_project_member_project
    ON project_member (project_id);

CREATE TABLE IF NOT EXISTS sdlc_run (
    id UUID PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    status VARCHAR(40) NOT NULL,
    current_stage VARCHAR(40) NOT NULL,
    requirement_hash VARCHAR(64),
    requirement_text TEXT,
    created_by_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sdlc_run_project
    ON sdlc_run (project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS sdlc_run_step (
    id UUID PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES sdlc_run (id) ON DELETE CASCADE,
    stage VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    conversation_id VARCHAR(120),
    workspace_ref TEXT,
    operation_id VARCHAR(80) NOT NULL,
    result_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, operation_id)
);

CREATE TABLE IF NOT EXISTS human_task (
    id UUID PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES sdlc_run (id) ON DELETE CASCADE,
    kind VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    assigned_role VARCHAR(80),
    bound_hash VARCHAR(64),
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    answered_by_email VARCHAR(255),
    answer_json JSONB,
    answered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_human_task_run
    ON human_task (run_id, status);

CREATE TABLE IF NOT EXISTS runner (
    id UUID PRIMARY KEY,
    owner_email VARCHAR(255) NOT NULL,
    name VARCHAR(120) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(40) NOT NULL DEFAULT 'OFFLINE',
    capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
    allowlist JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_heartbeat_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_runner_owner
    ON runner (lower(owner_email));

CREATE TABLE IF NOT EXISTS runner_job (
    id UUID PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES sdlc_run (id) ON DELETE CASCADE,
    step_id UUID REFERENCES sdlc_run_step (id) ON DELETE SET NULL,
    runner_id UUID REFERENCES runner (id) ON DELETE SET NULL,
    status VARCHAR(40) NOT NULL,
    placement VARCHAR(40) NOT NULL DEFAULT 'LOCAL_DOCKER',
    prompt TEXT,
    repo_allowlist JSONB NOT NULL DEFAULT '[]'::jsonb,
    claim_nonce VARCHAR(64),
    claimed_at TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    lease_until TIMESTAMPTZ,
    result_json JSONB,
    operation_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, operation_id)
);

CREATE INDEX IF NOT EXISTS idx_runner_job_claim
    ON runner_job (status, runner_id, lease_until);

CREATE TABLE IF NOT EXISTS job_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES runner_job (id) ON DELETE CASCADE,
    event_type VARCHAR(80) NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_event_job
    ON job_event (job_id, id);

CREATE TABLE IF NOT EXISTS event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID REFERENCES sdlc_run (id) ON DELETE CASCADE,
    event_type VARCHAR(80) NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS artifact (
    id UUID PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES sdlc_run (id) ON DELETE CASCADE,
    kind VARCHAR(80) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
