-- Figma design bindings used to snapshot screens and sync changes into Jira.

CREATE TABLE IF NOT EXISTS figma_design_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    file_key VARCHAR(80) NOT NULL,
    file_name VARCHAR(255),
    file_url VARCHAR(500),
    figma_project_id VARCHAR(80),
    team_id VARCHAR(80),
    sync_jira BOOLEAN NOT NULL DEFAULT TRUE,
    webhook_id VARCHAR(120),
    webhook_passcode VARCHAR(120),
    file_version VARCHAR(80),
    last_synced_at VARCHAR(40),
    last_sync_summary TEXT,
    webhook_status VARCHAR(120),
    snapshot_json TEXT,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_figma_design_project_file
    ON figma_design_binding (project_id, file_key);

CREATE INDEX IF NOT EXISTS idx_figma_design_file_key
    ON figma_design_binding (file_key);

CREATE INDEX IF NOT EXISTS idx_figma_design_passcode
    ON figma_design_binding (webhook_passcode);

ALTER TABLE figma_design_binding ADD COLUMN IF NOT EXISTS webhook_passcode VARCHAR(120);
ALTER TABLE figma_design_binding ADD COLUMN IF NOT EXISTS webhook_status VARCHAR(120);
ALTER TABLE figma_design_binding ADD COLUMN IF NOT EXISTS snapshot_json TEXT;
ALTER TABLE figma_design_binding ALTER COLUMN file_name TYPE TEXT;
ALTER TABLE figma_design_binding ALTER COLUMN file_url TYPE TEXT;
ALTER TABLE figma_design_binding ALTER COLUMN file_version TYPE TEXT;
ALTER TABLE figma_design_binding ALTER COLUMN webhook_status TYPE TEXT;
ALTER TABLE figma_design_binding ALTER COLUMN last_synced_at TYPE TEXT;
