package com.talentserv.blink.service;

import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.talentserv.blink.domain.Project;

@Service
public class SpringBootProjectGenerator {

    public Map<String, String> generate(Project project) {
        String artifact = ProjectCodes.artifact(project.getProjectName());
        String packageName = ProjectCodes.packageName(artifact);
        String packagePath = packageName.replace('.', '/');
        String classPrefix = toClassPrefix(artifact);
        String description = project.getDescription() == null || project.getDescription().isBlank()
                ? "Generated by Blink"
                : project.getDescription().strip();
        String projectName = project.getProjectName();

        Map<String, String> files = new LinkedHashMap<>();
        String root = artifact + "/";
        files.put(root + "pom.xml", pom(artifact, description));
        files.put(root + "README.md", readme(projectName, artifact, packageName));
        files.put(root + ".gitignore", "target/\n.idea/\n*.iml\n.env\n");
        files.put(root + "src/main/resources/application.yaml", applicationYaml());
        files.put(root + "src/main/java/" + packagePath + "/" + classPrefix + "Application.java",
                applicationClass(packageName, classPrefix));
        files.put(root + "src/main/java/" + packagePath + "/web/HelloController.java",
                helloController(packageName, projectName));
        return files;
    }

    private static String toClassPrefix(String artifact) {
        StringBuilder out = new StringBuilder();
        for (String part : artifact.split("-")) {
            if (part.isBlank()) {
                continue;
            }
            out.append(Character.toUpperCase(part.charAt(0)));
            if (part.length() > 1) {
                out.append(part.substring(1));
            }
        }
        return out.isEmpty() ? "Blink" : out.toString();
    }

    private static String pom(String artifact, String description) {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <parent>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-parent</artifactId>
                        <version>4.1.0</version>
                        <relativePath/>
                    </parent>
                    <groupId>com.example</groupId>
                    <artifactId>%s</artifactId>
                    <version>0.1.0</version>
                    <name>%s</name>
                    <description>%s</description>
                    <properties>
                        <java.version>25</java.version>
                    </properties>
                    <dependencies>
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-webmvc</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-actuator</artifactId>
                        </dependency>
                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-test</artifactId>
                            <scope>test</scope>
                        </dependency>
                    </dependencies>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-maven-plugin</artifactId>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                """.formatted(artifact, artifact, xmlEscape(description));
    }

    private static String applicationYaml() {
        return """
                server:
                  port: 8080
                spring:
                  application:
                    name: generated-app
                management:
                  endpoints:
                    web:
                      exposure:
                        include: health,info
                """;
    }

    private static String applicationClass(String packageName, String classPrefix) {
        return """
                package %s;

                import org.springframework.boot.SpringApplication;
                import org.springframework.boot.autoconfigure.SpringBootApplication;

                @SpringBootApplication
                public class %sApplication {

                    public static void main(String[] args) {
                        SpringApplication.run(%sApplication.class, args);
                    }
                }
                """.formatted(packageName, classPrefix, classPrefix);
    }

    private static String helloController(String packageName, String projectName) {
        return """
                package %s.web;

                import java.util.Map;

                import org.springframework.web.bind.annotation.GetMapping;
                import org.springframework.web.bind.annotation.RestController;

                @RestController
                public class HelloController {

                    @GetMapping("/")
                    public Map<String, String> hello() {
                        return Map.of(
                                "project", "%s",
                                "status", "generated-by-blink"
                        );
                    }
                }
                """.formatted(packageName, javaEscape(projectName));
    }

    private static String readme(String projectName, String artifact, String packageName) {
        return """
                # %s

                Spring Boot 4.1.0 service generated by Blink.

                - Artifact: `%s`
                - Package: `%s`
                - Java: 25

                ```bash
                mvn spring-boot:run
                ```
                """.formatted(projectName, artifact, packageName);
    }

    private static String xmlEscape(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private static String javaEscape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
